Not output reset in function colorize

diff --git a/bashu b/bashu
--- a/bashu
+++ b/bashu
@@ -186,7 +186,11 @@ colorize() {
   else
     text=$*
   fi
-  printf "%s%s%s%s" "$(tput setaf "${__palette[$col]}")" "$text" "$(tput sgr0)" "$newline"
+  printf "%s%s%s" "$(tput setaf "${__palette[$col]}")" "$text" "$newline"
+}
+
+reset() {
+  printf "%s" "$(tput sgr0)"
 }
 
 # Helper function `_logfmt` takes the logging level as the first
@@ -202,13 +206,13 @@ _logfmt() {
 # Utility function `error` prints an error message to the user, which
 # is redirected to the standard error.
 error() {
-  _logfmt "$(colorize maroon error)" 2 "$@" >&2
+  _logfmt "$(colorize red error)$(reset)" 2 "$@" >&2
 }
 
 # Utility function `warn` prints a warning message to the user, which
 # is redirected to the standard error.
 warn() {
-  _logfmt "$(colorize navy warning)" 2 "$@" >&2
+  _logfmt "$(colorize blue warning)$(reset)" 2 "$@" >&2
 }
 
 # Utility function `debug` prints a debug message to the developer
@@ -216,7 +220,7 @@ warn() {
 is_debugging=0
 debug() {
   if (( is_debugging )); then
-    _logfmt "$(colorize olive debug)" 2 "$@" >&2
+    _logfmt "$(colorize yellow debug)$(reset)" 2 "$@" >&2
   fi
 }
 
@@ -224,7 +228,7 @@ debug() {
 # to the developer, which is redirected to the standard error. Since
 # it implies a bug, it should be fixed as soon as possible.
 internal_error() {
-  _logfmt "$(colorize maroon "bashu internal error")" 2 "$@" >&2
+  _logfmt "$(colorize red "bashu internal error")$(reset)" 2 "$@" >&2
 }
 
 # Utility function `horizln` draws a horizontal line that expands
@@ -760,14 +764,14 @@ _bashu_formatter_result_default() {
   bashu_current_test=$_bashu_current_test
   bashu_is_failed=$_bashu_is_failed
   if (( ! bashu_is_failed )); then
-    colorize -n green "."
+    colorize -n green "."; reset
   else
     bashu_err_funcname=("${_bashu_err_funcname[@]}")
     bashu_err_source=("${_bashu_err_source[@]}")
     bashu_err_lineno=("${_bashu_err_lineno[@]}")
     # shellcheck disable=SC2034
     bashu_err_status=$_bashu_err_status
-    colorize -n maroon "F"
+    colorize -n maroon "F"; reset
   fi
 }
 
@@ -952,13 +956,13 @@ _bashu_formatter_summary_default_each_failure() {
 
   bashu_err_trace_stack_get "$index" "err_trace"
   bashu_err_trace_stack_cut "${err_trace[0]}" "err_info"
-  horizln '_' "${err_info[0]}" | colorize red
-  printf "\n"
+  horizln '_' "${err_info[0]}" | colorize -n red; reset
+  printf "\n\n"
   _bashu_formatter_summary_default_show_failed_code "${err_info[@]}"
-  _bashu_formatter_summary_default_show_evaluated_code "${err_trace[@]}" | colorize red
-  printf "\n"
+  _bashu_formatter_summary_default_show_evaluated_code "${err_trace[@]}" | colorize -n red; reset
+  printf "\n\n"
   bashu_err_trace_stack_cut "${err_trace[-1]}" "err_info"
-  colorize -n red "${err_info[2]}"
+  colorize -n red "${err_info[2]}"; reset
   printf ":%s: Exit with %d\n" "${err_info[3]}" "${bashu_err_status_stack[$index]}"
 }
 
@@ -982,15 +986,18 @@ _bashu_formatter_summary_default_footer() {
 
   t_sec=$(bc -l <<<"${bashu_total_execution_time} / 1000")
   if (( ! n_passed )); then
-    printf "%d failed " "$n_failed" | colorize -n red
-    printf "in %.2fs" "$t_sec" | colorize maroon
+    printf "%d failed " "$n_failed" | colorize -n red; reset
+    printf "in %.2fs" "$t_sec" | colorize -n red; reset
+    printf "\n"
   elif (( ! n_failed )); then
-    printf "%d passed " "$n_passed" | colorize -n lime
-    printf "in %.2fs" "$t_sec" | colorize green
+    printf "%d passed " "$n_passed" | colorize -n green; reset
+    printf "in %.2fs" "$t_sec" | colorize -n green; reset
+    printf "\n"
   else
-    printf "%d failed" "$n_failed" | colorize -n red
+    printf "%d failed" "$n_failed" | colorize -n red; reset
     printf ", "
-    printf "%d passed " "$n_passed" | colorize -n green
-    printf "in %.2fs" "$t_sec" | colorize maroon
+    printf "%d passed " "$n_passed" | colorize -n green; reset
+    printf "in %.2fs" "$t_sec" | colorize -n red; reset
+    printf "\n"
   fi
 }
